openapi: 3.0.0
info:
  title: title
  version: version
servers:
  - url: http://localhost:8080/api/v1
tags:
  - name: album-resource-rest-controller
  - name: album-base64-rest-controller
  - name: album-pageable-rest-controller
  - name: album-crud-rest-controller
paths:
  /images/resource/{id}:
    get:
      operationId: getResource
      tags:
        - album-resource-rest-controller
      description: |
        get image resource
      parameters:
        - $ref: '../album.parameters.yaml#/parameters/id'
      responses:
        '200':
          description: |
            ok
          content:
            '*/*':
              schema:
                type: string
                format: binary
        '404':
          description: |
            can't get image resource
        '400':
          description: |
            can't get image resource
        '5XX':
          description: |
            can't get image resource
  /images/base64/{id}:
    get:
      operationId: getBase64
      tags:
        - album-base64-rest-controller
      description: |
        get base64 image
      parameters:
        - $ref: '../album.parameters.yaml#/parameters/id'
      responses:
        '200':
          description: |
            ok
          content:
            '*/*':
              schema:
                type: string
                format: base64
        '404':
          description: |
            can't get base64 image
        '400':
          description: |
            can't get base64 image
        '5XX':
          description: |
            can't get base64 image
  /images:
    get:
      operationId: getImages
      tags:
        - album-pageable-rest-controller
      description: |
        get pageable images
      parameters:
        - $ref: '../album.parameters.yaml#/parameters/page'
        - $ref: '../album.parameters.yaml#/parameters/pageSize'
        - $ref: '../album.parameters.yaml#/parameters/sortBy'
        - $ref: '../album.parameters.yaml#/parameters/sortDirection'
      responses:
        '200':
          description: |
            ok
          content:
            application/json:
              schema:
                $ref: '../album.schemes.yaml#/schemes/ImageDtoArray'
        '400':
          description: |
            can't get pageable images
        '5XX':
          description: |
            can't get pageable images
    post:
      operationId: create
      tags:
        - album-crud-rest-controller
      description: |
        create image
      parameters:
        - $ref: '../album.parameters.yaml#/parameters/filename'
        - $ref: '../album.parameters.yaml#/parameters/contentType'

      # resource
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              format: binary

      responses:
        '200':
          description: |
            ok
          content:
            application/json:
              schema:
                $ref: '../album.schemes.yaml#/schemes/ImageDto'
        '400':
          description: |
            can't create image
        '5XX':
          description: |
            can't create image
  /images/{id}:
    delete:
      operationId: delete
      tags:
        - album-crud-rest-controller
      description: |
        delete image
      parameters:
        - $ref: '../album.parameters.yaml#/parameters/id'
      responses:
        '200':
          description: |
            ok
        '404':
          description: |
            can't delete image
        '400':
          description: |
            can't delete image
        '5XX':
          description: |
            can't delete image
