version: '1.0-SNAPSHOT'
services:
  album-rest-api-service:
    image: 'album-rest-api:latest'
    build:
      context: .
    container_name: album-rest-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres-service
    environment:
      - SPRING_DATASOURCE_URL= # specify
      - SPRING_DATASOURCE_USERNAME= # specify
      - SPRING_DATASOURCE_PASSWORD= # specify
  postgres-service:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER= # specify
      - POSTGRES_PASSWORD= # specify
